### PR TITLE
fix(presentation): middleware ordering

### LINKED ISSUE #27: Panic during startup
```
2023-06-12 12:23:33 goroutine 1 [running]:
2023-06-12 12:23:33 github.com/go-chi/chi/v5.(*Mux).Use(...)
2023-06-12 12:23:33     /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:102
2023-06-12 12:23:33 mock-payment-provider/presentation.NewPresenter({{0xc00001c026, 0x7}, {0xc00002000a, 0x4}, {0xc00001e00b, 0xf}, 0xc000022180})
2023-06-12 12:23:33     /app/presentation/presentation.go:53 +0x9a6
2023-06-12 12:23:33 main.main()
2023-06-12 12:23:33     /app/main.go:82 +0xa8d
2023-06-12 12:23:40 panic: chi: all middlewares must be defined before routes on a mux
```

### PR DESCRIPTION
**Pull request by aldy505**
Closes #27

### CODE REVIEW

**Review by WahidinAji — APPROVED** [review]
GBTM

**Comment by aldy505** [comment]
@YogiPristiawan mau review?

**Comment by yogip07** [comment]
sorean gpp pak?

**Comment by aldy505** [comment]
> sorean gpp pak?

gpp

**Review by yogip07 — APPROVED** [review]
LGTM. baru sempet :D

**Pull request merged**
